require([

	'app',
	'bbloader',
	'names',

	'modules/devtools/Module',
	'modules/dialog/Module',

	'models/Question',
	'models/Answer',
	'models/QuestionsFilter',
	'models/Abgeordnete',
	'models/Result',

	'collections/Questions',
	'collections/Answers',

	'views/questions-compositeview/QuestionsCompositeView',
	'views/questionsfilter-itemview/QuestionsFilterView',
	'views/result-itemview/ResultView',
	'views/bottom-itemview/BottomView',

	'data/questions' // generated by import_csv.py

], function(

	App,
	Backbone,
	__unused__,

	DevtoolsModule,
	DialogModule,

	Question,
	Answer,
	QuestionsFilter,
	Abgeordnete,
	Result,

	Questions,
	Answers,

	QuestionsView,
	QuestionsFilterView,
	ResultView,
	BottomView,

	data_questions
) {

	App.modules = {};

	App.model = new Backbone.Model({
		defaults: {
			selected_party: null,
			evaluated: false
		}
	});

	function show_filter() {
		var questions_filter = new QuestionsFilterView({
			model: App.data.questions_filter
		});
		App.layout.region_filter.show(questions_filter);
		App.listenTo(questions_filter, 'filter-toggle', function(model, field, value) {
			model.set(field, value);
		});
	}
	
	function show_results() {
		var result_view = new ResultView({ model: App.data.result });
		App.layout.region_result.show(result_view);
		App.evaluated = true;
		App.model.set('evaluated', true);
		App.layout.$el.addClass('evaluated');
		result_view.on('party-selected', function(party, selected) {
			var selected_party = App.model.get('selected_party');
			if (selected) {
				App.model.set('selected_party', party);
			} else {
				App.model.set('selected_party', null);
			}
			// questions_table.selectParty(party, selected);
		});
	}

	function show_all_averages() {
		App.layout.region_table.currentView.showAverages();
	}

	function do_analysis() {
		if (App.data.questions) {
			// show_filter();
			App.data.result = new Result(App.data.user_answers, App.data.abgeordnete);
			show_results();
			show_all_averages();
		}
	}

	function answer_select(view, value) {
		App.data.user_answers.at(view.model.id).set('value', value);
	}

	function answer_weight_toggle(view, value) {
		App.data.user_answers.at(view.model.id).set('double_weight', value);
	}

	App.addInitializer(function() {
		App.modules.dialog   = new DialogModule();
		if (window.MODE == 'DEV' || window.MODE == 'DEBUG')
			App.modules.devtools = new DevtoolsModule();
	});

	App.start();

	// Evaluation done?
	App.evaluated = false;

	// init app data
	App.data.questions = new Questions(data_questions);
	App.data.user_answers = new Answers();
	App.data.questions.each(function(q) {
		App.data.user_answers.add(new Answer(q.id));
	});
	App.data.questions_filter = new QuestionsFilter();
	App.data.abgeordnete = new Abgeordnete();
	App.data.abgeordnete.load();

	// question table
	var questions_table = new QuestionsView({ collection: App.data.questions });
	App.layout.region_table.show(questions_table);
	App.listenTo(questions_table, 'itemview:answer-select', answer_select);
	App.listenTo(questions_table, 'itemview:answer-weight-toggle', answer_weight_toggle);

	App.listenTo(questions_table, 'num-answered', function(num_answered) {
		bottom_view.displayNumAnswered(num_answered);
	});

	// bottom
	var bottom_view = new BottomView();
	App.layout.region_result.show(bottom_view);
	App.listenToOnce(bottom_view, 'start', function() {
		App.layout.region_bottom.close();
		do_analysis();
		App.layout.region_table.currentView.scrollToTop();
	});

});
